server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # scrape logs locally from stock-app
  - job_name: stock-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: stock-app-logs
          __path__: /home/ec2-user/stock-app/logs/*.log